version: '3'

services:

  nginx:
    build: docker/nginx
    container_name: nginx
    links:
      - php
    ports:
      - 80
    working_dir: /application
    volumes:
      - ./:/application:cached

  php:
    build: docker/php
    container_name: php
    depends_on:
      - elasticsearch
      - mariadb
      - redis
    links:
      - elasticsearch
      - mariadb
      - redis
    working_dir: /application
    volumes:
      - ./:/application:cached
    env_file:
      - .env

  worker:
    build: docker/php-worker
    container_name: worker
    depends_on:
      - elasticsearch
      - mariadb
      - redis
    links:
      - elasticsearch
      - mariadb
      - redis
    working_dir: /application
    restart: always
    command: ["php", "artisan", "horizon"]
    volumes:
      - ./:/application:cached
    env_file:
      - .env

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3306
    volumes:
      - ./storage/database:/var/lib/mysql:cached
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis
    restart: always

  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    ports:
      - 9200
      - 9300
    volumes:
      - ./storage/elasticsearch:/usr/share/elasticsearch/data:cached

  node:
    image: node
    container_name: node
    restart: always
    depends_on:
      - redis
    links:
      - redis
    working_dir: /application
    volumes:
      - ./:/application:cached
    command: ["node", "socket.js"]
