version: '3'

services:

  nginx:
    container_name: nginx
    build: ./services/nginx
    links:
      - php
    ports:
      - 8080:80
    working_dir: /application
    volumes:
      - ../:/application:cached
    env_file:
      - .env

  php:
    container_name: php
    build: ./services/php
    links:
      - mariadb
      - redis
    working_dir: /application
    volumes:
      - ../:/application:cached
    env_file:
      - .env

  worker:
    container_name: worker
    build: ./services/php-worker
    links:
      - redis
      - elasticsearch
    working_dir: /application
    restart: always
    command: ["php", "artisan", "horizon"]
    volumes:
      - ../:/application:cached
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    volumes:
      - ../storage/database:/var/lib/mysql:cached
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis
    restart: always
    env_file:
      - .env

  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ../storage/elasticsearch:/usr/share/elasticsearch/data